# Use the official Node.js image with the desired version
FROM node:18.3.0

# Set the working directory inside the container
# WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 3000 (default port for React apps)
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
