version: '3.8'

services:
  frontend:
    build: ./frontend   # Path to the directory containing the frontend Dockerfile
    ports:
      - "3000:3000"     # Map container port 3000 to host port 3000
    volumes:
      - ./frontend:/app # Mount the frontend directory to /app in the container
    depends_on:
      - backend

  backend:
    build: ./backend    # Path to the directory containing the backend Dockerfile
    ports:
      - "8080:8080"     # Map container port 8080 to host port 8080
    volumes:
      - ./backend:/app  # Mount the backend directory to /app in the container
