# Use the official Node.js image with the desired version
FROM node:18.3.0

#nodemon
RUN npm install -g nodemon

#workdir
# WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 8080
EXPOSE 8080

# Use Nodemon for automatic restarts
CMD ["npm", "run","dev"]
